# Generated by Django 3.2 on 2023-04-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_categories_genres'),
        ('reviews', '0004_alter_user_password'),
    ]

    operations = [
    ]
