# Generated by Django 3.2 on 2023-04-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_titles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ['id']},
        ),
    ]
